"""empty message

Revision ID: 109cf52975dd
Revises: 
Create Date: 2019-02-21 08:13:10.023506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109cf52975dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('post_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent', 'post_by')
    # ### end Alembic commands ###
